'use client';
import { useEffect, useMemo, useState } from 'react';
import { AreaChart, Area, ResponsiveContainer, XAxis, YAxis, Tooltip, BarChart, Bar, PieChart, Pie, Cell } from 'recharts';
import { Brain, GraduationCap, Newspaper, ShieldCheck, Lock, Radio, Activity, Briefcase, Settings, Send, LineChart, Users, Gauge, ExternalLink } from 'lucide-react';
import { tiers, Tier, canAccess } from '@/lib/tiers';
import { auditLogs, lessons } from '@/lib/mock';
import type { MarketQuote, NewsItem } from '@/lib/types';

const nav = [
  ['Overview', Activity], ['Ask AIMi', Brain], ['Learn', GraduationCap], ['Insights', Newspaper], ['Signals', Radio], ['FinLLAMA Quant', LineChart], ['Broker Hand-off', ExternalLink], ['Admin', Settings], ['Compliance', ShieldCheck]
] as const;

function Card({children, className=''}:{children:React.ReactNode; className?:string}){return <div className={`card p-5 ${className}`}>{children}</div>}
function Locked({required}:{required:Tier}){return <div className="mt-4 rounded-2xl border border-amber-300/30 bg-amber-300/10 p-4 text-sm text-amber-100 flex gap-3"><Lock size={18}/> Tier {required}+ required. Upgrade to unlock this intelligence layer.</div>}

export default function Dashboard(){
  const [active,setActive]=useState('Overview'); const [tier,setTier]=useState<Tier>(5); const [quotes,setQuotes]=useState<MarketQuote[]>([]); const [news,setNews]=useState<NewsItem[]>([]); const [signals,setSignals]=useState<any[]>([]); const [admin,setAdmin]=useState<any>(null); const [msg,setMsg]=useState('What is the current market regime?'); const [chat,setChat]=useState<any[]>([]);
  useEffect(()=>{ fetch('/api/market').then(r=>r.json()).then(j=>setQuotes(j.data||[])); fetch('/api/news').then(r=>r.json()).then(j=>setNews(j.items||[])); fetch('/api/signals').then(r=>r.json()).then(j=>setSignals(j.signals||[])); fetch('/api/admin').then(r=>r.json()).then(setAdmin); },[]);
  const selected = quotes[0]; const tierInfo = tiers.find(t=>t.id===tier)!;
  async function ask(){ if(!msg.trim())return; const user={role:'user',text:msg}; setChat(c=>[...c,user]); setMsg(''); const res=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:msg,tier,riskProfile:'Balanced'})}); const j=await res.json(); setChat(c=>[...c,{role:'aimi',text:j.answer,source:j.source}]); }
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#7c3aed55,transparent_35%),radial-gradient(circle_at_bottom_right,#06b6d455,transparent_35%),#070315]">
    <aside className="fixed left-0 top-0 hidden h-full w-72 border-r border-white/10 bg-black/25 p-5 backdrop-blur-xl lg:block">
      <div className="mb-8 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-fuchsia-500 shadow-glow"><Brain/></div><div><h1 className="text-xl font-bold">AIMi</h1><p className="text-xs text-white/55">AI Wealth Intelligence</p></div></div>
      <div className="space-y-2">{nav.map(([n,Icon])=><button key={n} onClick={()=>setActive(n)} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm ${active===n?'bg-white text-slate-950':'text-white/75 hover:bg-white/10'}`}><Icon size={18}/>{n}</button>)}</div>
      <Card className="mt-6"><p className="text-xs text-white/50">Current access</p><select value={tier} onChange={e=>setTier(Number(e.target.value) as Tier)} className="mt-2 w-full rounded-xl bg-black/40 p-2">{tiers.map(t=><option key={t.id} value={t.id}>Tier {t.id} — {t.name}</option>)}</select><p className="mt-3 text-sm text-fuchsia-100">{tierInfo.price}</p></Card>
    </aside>
    <section className="lg:pl-72"><header className="sticky top-0 z-20 border-b border-white/10 bg-[#070315]/80 p-4 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="text-sm text-fuchsia-200">chataimi.ai dashboard</p><h2 className="text-2xl font-bold">{active}</h2></div><div className="pill px-4 py-2 text-sm">Tier {tier}: {tierInfo.name}</div></div></header>
    <div className="mx-auto max-w-7xl p-4 md:p-8">{active==='Overview'&&<Overview quotes={quotes} selected={selected} news={news} admin={admin}/>} {active==='Ask AIMi'&&<Ask chat={chat} msg={msg} setMsg={setMsg} ask={ask}/>} {active==='Learn'&&<Learn tier={tier}/>} {active==='Insights'&&<Insights news={news}/>} {active==='Signals'&&<Signals tier={tier} signals={signals}/>} {active==='FinLLAMA Quant'&&<Quant tier={tier} quotes={quotes} signals={signals}/>} {active==='Broker Hand-off'&&<Broker/>} {active==='Admin'&&<Admin admin={admin}/>} {active==='Compliance'&&<Compliance/>}</div></section></main>
}
function Overview({quotes,selected,news,admin}:any){return <div className="grid gap-5"><div className="grid gap-5 md:grid-cols-4"><Metric title="Active users" value="1,470"/><Metric title="MRR" value={`£${admin?.mrr?.toLocaleString?.()||'—'}`}/><Metric title="Broker clicks" value={admin?.brokerClicks||'—'}/><Metric title="Risk score" value="64/100"/></div><div className="grid gap-5 lg:grid-cols-3"><Card className="lg:col-span-2"><h3 className="font-semibold">Live market watch</h3><p className="text-sm text-white/50">Runtime data via /api/market. Uses Yahoo chart API with demo fallback.</p><div className="mt-4 h-72">{selected&&<ResponsiveContainer><AreaChart data={selected.points}><XAxis dataKey="date" hide/><YAxis hide domain={['dataMin','dataMax']}/><Tooltip/><Area type="monotone" dataKey="close" fillOpacity={0.25}/></AreaChart></ResponsiveContainer>}</div><div className="mt-4 grid gap-2 md:grid-cols-3">{quotes.slice(0,9).map((q:MarketQuote)=><div key={q.symbol} className="rounded-2xl bg-white/5 p-3"><b>{q.symbol}</b><p>{q.price}</p><span className={q.changePct>=0?'text-emerald-300':'text-rose-300'}>{q.changePct}%</span></div>)}</div></Card><Card><h3 className="font-semibold">AIMi intelligence feed</h3><div className="mt-4 space-y-3">{news.slice(0,5).map((n:NewsItem,i:number)=><p key={i} className="rounded-2xl bg-white/5 p-3 text-sm">{n.title}<br/><span className="text-white/45">{n.source}</span></p>)}</div></Card></div></div>}
function Metric({title,value}:any){return <Card><p className="text-sm text-white/50">{title}</p><h3 className="mt-2 text-3xl font-bold">{value}</h3></Card>}
function Ask({chat,msg,setMsg,ask}:any){return <Card><h3 className="text-xl font-semibold">Ask AIMi</h3><p className="text-sm text-white/55">Tier-aware, compliance-safe chat. Connect Gemini with GOOGLE_GENERATIVE_AI_API_KEY.</p><div className="mt-5 h-[460px] overflow-auto rounded-3xl bg-black/25 p-4">{chat.length===0&&<p className="text-white/45">Try: “Explain portfolio risk in plain English” or “What does Risk-On mean?”</p>}{chat.map((m:any,i:number)=><div key={i} className={`my-3 max-w-3xl rounded-2xl p-4 ${m.role==='user'?'ml-auto bg-fuchsia-500':'bg-white/10'}`}><p className="whitespace-pre-wrap text-sm">{m.text}</p>{m.source&&<p className="mt-2 text-xs text-white/45">Source: {m.source}</p>}</div>)}</div><div className="mt-4 flex gap-3"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} className="flex-1 rounded-2xl bg-white/10 px-4 outline-none"/><button onClick={ask} className="rounded-2xl bg-white px-5 py-3 text-slate-950"><Send size={18}/></button></div></Card>}
function Learn({tier}:{tier:Tier}){return <div className="grid gap-5 md:grid-cols-2">{lessons.map(l=><Card key={l.title}><div className="flex items-start justify-between"><div><p className="text-xs text-fuchsia-200">Tier {l.tier} • {l.type}</p><h3 className="mt-1 text-lg font-semibold">{l.title}</h3></div>{!canAccess(tier,l.tier as Tier)&&<Lock/>}</div><div className="mt-5 h-2 rounded-full bg-white/10"><div className="h-2 rounded-full bg-fuchsia-300" style={{width:`${canAccess(tier,l.tier as Tier)?l.progress:0}%`}}/></div></Card>)}</div>}
function Insights({news}:any){return <div className="grid gap-4">{news.map((n:NewsItem,i:number)=><Card key={i}><p className="text-xs text-white/45">{n.source} {n.publishedAt?`• ${new Date(n.publishedAt).toLocaleString()}`:''}</p><h3 className="mt-1 text-lg font-semibold">{n.title}</h3><p className="mt-2 text-sm text-white/55">AIMi context: monitor whether this reinforces Risk-On, Risk-Off or Transition conditions.</p></Card>)}</div>}
function Signals({tier,signals}:any){return <Card><h3 className="text-xl font-semibold">Tier 4–5 Signals Intelligence</h3>{!canAccess(tier,4)&&<Locked required={4}/>}<div className="mt-5 overflow-x-auto"><table className="w-full text-sm"><thead className="text-white/45"><tr>{['Asset','Strategy','Direction','Confidence','Risk','Entry','Horizon','Impact'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{signals.map((s:any)=><tr key={s.asset} className="border-t border-white/10 opacity-100"><td className="p-3 font-bold">{s.asset}</td><td className="p-3">{s.strategy}</td><td className="p-3">{canAccess(tier,4)?s.direction:'Locked'}</td><td className="p-3">{canAccess(tier,4)?`${s.confidence}%`:'—'}</td><td className="p-3">{s.risk}</td><td className="p-3">{canAccess(tier,4)?s.entry:'—'}</td><td className="p-3">{s.horizon}</td><td className="p-3">{s.impact}</td></tr>)}</tbody></table></div><p className="mt-4 text-xs text-white/45">Signals are non-personalised market intelligence, not instructions to trade.</p></Card>}
function Quant({tier,quotes,signals}:any){const bars=signals.map((s:any)=>({name:s.strategy,confidence:s.confidence}));return <div className="grid gap-5">{!canAccess(tier,5)&&<Locked required={5}/>}<div className="grid gap-5 lg:grid-cols-3"><Card><h3 className="font-semibold">Regime AI</h3><div className="mt-6 grid place-items-center"><Gauge size={86}/><h2 className="mt-3 text-3xl font-bold">Transition</h2><p className="text-white/50">Risk environment score: 64</p></div></Card><Card className="lg:col-span-2"><h3 className="font-semibold">Strategy suitability matrix</h3><div className="h-72"><ResponsiveContainer><BarChart data={bars}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="confidence"/></BarChart></ResponsiveContainer></div></Card></div><div className="grid gap-5 lg:grid-cols-2"><Card><h3 className="font-semibold">FinLLAMA reasoning layer</h3><p className="mt-3 text-sm text-white/65">Synthesises weighted candidate signals, regime state, feature context, RAG evidence bundles and portfolio risk tags into structured explainable signal objects.</p><div className="mt-4 rounded-2xl bg-black/30 p-4 text-xs text-fuchsia-100">JSON-first output: asset, direction, confidence, risk_class, time_horizon, strategy_alignment, evidence_strength, invalidation_conditions, rationale_summary.</div></Card><Card><h3 className="font-semibold">Portfolio risk map</h3><div className="mt-4 grid grid-cols-3 gap-2">{['AI beta','Mega-cap tech','Crypto vol','Gold hedge','Oil beta','USD rates','Equity beta','Momentum','Vol shock'].map((x,i)=><div key={x} className={`rounded-2xl p-4 text-center text-xs ${i%3===0?'bg-rose-400/20':i%3===1?'bg-amber-300/20':'bg-emerald-300/20'}`}>{x}</div>)}</div></Card></div></div>}
function Broker(){return <div className="grid gap-5 md:grid-cols-2"><Card><h3 className="text-xl font-semibold">Broker hand-off only</h3><p className="mt-3 text-white/60">AIMi never executes trades, never holds funds, and never modifies broker-side data. Buy/Sell intent buttons show exit confirmation and redirect to the user’s broker.</p><button className="mt-5 rounded-2xl bg-white px-5 py-3 text-slate-950">Show exit confirmation</button></Card><Card><h3 className="font-semibold">Partner tracking</h3><p className="mt-3 text-sm text-white/60">Configure referral parameters, conversion events and revenue attribution in Admin. API keys belong in server env variables only.</p></Card></div>}
function Admin({admin}:any){const data=(admin?.usersByTier||[]).map((v:number,i:number)=>({name:`T${i+1}`,users:v}));return <div className="grid gap-5 lg:grid-cols-2"><Card><h3 className="font-semibold">Users by tier</h3><div className="h-72"><ResponsiveContainer><BarChart data={data}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="users"/></BarChart></ResponsiveContainer></div></Card><Card><h3 className="font-semibold">Operational controls</h3>{['Tier & pricing management','Learning content CMS','Signals approval queue','RAG source controls','Automation scheduler','Moderation review'].map(x=><div key={x} className="mt-3 rounded-2xl bg-white/5 p-3 text-sm">{x}</div>)}</Card></div>}
function Compliance(){return <div className="grid gap-5 md:grid-cols-2"><Card><h3 className="font-semibold">Audit trail</h3>{auditLogs.map(l=><p key={l} className="mt-3 rounded-2xl bg-white/5 p-3 text-sm">{l}</p>)}</Card><Card><h3 className="font-semibold">Disclosures</h3><p className="mt-3 text-sm text-white/60">AIMi is an educator, guide and decision-intelligence layer. It is not a broker, robo-trader or autonomous financial advisor. All advanced outputs are controlled by membership tier, risk profiling and compliance guardrails.</p></Card></div>}
